
#ifndef _INCLUDE_SOURCEMOD_EXTENSION_CONFIG_H_
#define _INCLUDE_SOURCEMOD_EXTENSION_CONFIG_H_
#define SMEXT_CONF_ERRORLENGTH      256
#define SMEXT_CONF_PREASEMBLYFUNC    0
#define SMEXT_CONF_POSTREADFUNC     0
#define SMEXT_CONF_ALLOWLATELOAD    0
#define SMEXT_CONF_VERSION        0x0001
#define SMEXT_LINK(name) SDKExtension *g_pExtensionIface = name;

#endif // _INCLUDE_SOURCEMOD_EXTENSION_CONFIG_H_#pragma once
